# Generated by Django 4.2.1 on 2023-07-04 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_app', '0003_cardmodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='videomodel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('videoname', models.CharField(max_length=30)),
                ('video', models.FileField(upload_to='django_app/static')),
                ('audioname', models.CharField(max_length=30)),
                ('audio', models.FileField(upload_to='django_app/static')),
                ('pdfname', models.CharField(max_length=30)),
                ('pdf', models.FileField(upload_to='django_app/static')),
            ],
        ),
    ]
