# Generated by Django 4.2.1 on 2023-07-08 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_app', '0004_videomodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='datemodel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('date', models.DateField()),
            ],
        ),
    ]
